version: "3"
services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql_master
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql-master:/var/lib/mysql
      - ./volume/conf/mysqld-master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./shell/ms.sh:/ms.sh
    environment:
      MYSQL_ROOT_PASSWORD: aq1sw2de
      MYSQL_DATABASE: BIG
      MYSQL_USER: bigadmin
      MYSQL_PASSWORD: aq1sw2de
    restart: unless-stopped
    networks:
      mysql-ms-network:
        ipv4_address: 172.25.0.101
  mysql-slave1:
    image: mysql:5.7
    container_name: mysql_slave1
    ports:
      - 3307:3306
    volumes:
      - ./volume/mysql-slave1:/var/lib/mysql
      - ./volume/conf/mysqld-slave1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: aq1sw2de
      MYSQL_DATABASE: BIG
      MYSQL_USER: bigadmin
      MYSQL_PASSWORD: aq1sw2de
    restart: unless-stopped
    networks:
      mysql-ms-network:
        ipv4_address: 172.25.0.102
  mysql-slave2:
    image: mysql:5.7
    container_name: mysql_slave2
    ports:
      - 3308:3306
    volumes:
      - ./volume/mysql-slave2:/var/lib/mysql
      - ./volume/conf/mysqld-slave2.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: aq1sw2de
      MYSQL_DATABASE: BIG
      MYSQL_USER: bigadmin
      MYSQL_PASSWORD: aq1sw2de
    restart: unless-stopped
    networks:
      mysql-ms-network:
        ipv4_address: 172.25.0.103
networks:
  mysql-ms-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
